#!/bin/bash
# install.sh - Install clank scripts and skills
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLANK_RC="$HOME/.clankrc"

echo "== Clank Installer =="
echo ""

# --- Check dependencies ---
MISSING=()
for cmd in tmux fzf gh claude bat jq bk; do
  if ! command -v "$cmd" &>/dev/null; then
    MISSING+=("$cmd")
  fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
  echo "Error: Missing required dependencies:"
  for cmd in "${MISSING[@]}"; do
    echo "  - $cmd"
  done
  echo ""
  echo "Install them before running this script."
  exit 1
fi

echo "All dependencies found."
echo ""

# --- Generate ~/.clankrc ---
if [ -f "$CLANK_RC" ]; then
  echo "Config file already exists: $CLANK_RC"
  read -p "Overwrite? [y/N] " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Keeping existing config."
    SKIP_CONFIG=1
  fi
fi

if [ -z "$SKIP_CONFIG" ]; then
  echo "Press Enter to accept the default value shown in [brackets]."
  echo ""

  read -p "Project directory [$HOME/dev/hox]: " WORK_DIR
  WORK_DIR="${WORK_DIR:-$HOME/dev/hox}"

  read -p "Session name [clank]: " SESSION_NAME
  SESSION_NAME="${SESSION_NAME:-clank}"

  read -p "Plans directory [$HOME/.claude/plans]: " PLANS_DIR
  PLANS_DIR="${PLANS_DIR:-$HOME/.claude/plans}"

  read -p "Linear team name (required): " LINEAR_TEAM
  while [ -z "$LINEAR_TEAM" ]; do
    read -p "Linear team name cannot be empty: " LINEAR_TEAM
  done

  cat > "$CLANK_RC" <<EOF
# Clank configuration - generated by install.sh
CLANK_WORK_DIR="$WORK_DIR"
CLANK_SESSION="$SESSION_NAME"
CLANK_PLANS_DIR="$PLANS_DIR"
CLANK_LINEAR_TEAM="$LINEAR_TEAM"
EOF

  echo "Config written to $CLANK_RC"
  echo ""
fi

# --- Symlink scripts ---
read -p "Symlink directory [$HOME/bin]: " BIN_DIR
BIN_DIR="${BIN_DIR:-$HOME/bin}"
mkdir -p "$BIN_DIR"

for script in "$SCRIPT_DIR"/bin/*; do
  name=$(basename "$script")
  ln -sf "$script" "$BIN_DIR/$name"
  echo "  Linked: $name -> $BIN_DIR/$name"
done
echo ""

# --- Symlink skills ---
SKILLS_DIR="$HOME/.claude/skills"
mkdir -p "$SKILLS_DIR"
for skill_dir in "$SCRIPT_DIR"/skills/*/; do
  skill_name=$(basename "$skill_dir")
  ln -sfn "$skill_dir" "$SKILLS_DIR/$skill_name"
  echo "  Linked skill: $skill_name -> $SKILLS_DIR/$skill_name"
done
echo ""

# --- Next steps ---
echo "== Installation complete =="
echo ""
echo "Next steps:"
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
  echo "  1. Add $BIN_DIR to your PATH:"
  echo "     export PATH=\"$BIN_DIR:\$PATH\""
fi
if [ -z "$LINEAR_API_KEY" ]; then
  echo "  2. Set LINEAR_API_KEY in your shell profile:"
  echo "     export LINEAR_API_KEY=\"lin_api_...\""
fi
echo "  3. Install the superpowers plugin (if not already):"
echo "     claude plugins add superpowers"
echo ""
echo "Run 'clank' to start!"
